<?php

declare(strict_types=1);

namespace App\Core\Evolution\Design;

/**
 * DesignComponentLibrary — persistent storage for DesignAgent-generated components.
 *
 * Components saved as Twig fragments in:
 *   src/resources/views/evolution/components/{name}.twig
 *
 * Metadata in:
 *   storage/evolution/design_library.json
 */
final class DesignComponentLibrary
{
    private const COMPONENT_DIR  = 'resources/views/evolution/components';
    private const GENERATED_DIR  = 'resources/views/evolution/components/generated';
    private const METADATA_FILE  = 'storage/evolution/design_library.json';

    // ─── Public API ───────────────────────────────────────────────────────────

    /**
     * Save a component to the library.
     * Returns the relative path to the saved file.
     */
    public function save(string $name, string $html, array $metadata = []): string
    {
        $name    = $this->sanitizeName($name);
        $base    = $this->base();
        $dir     = $base . '/' . self::GENERATED_DIR;

        if (!is_dir($dir)) {
            @mkdir($dir, 0755, true);
        }

        $filename = $name . '.twig';
        $path     = $dir . '/' . $filename;

        // Add Twig comment header
        $header   = "{# Component: {$name} | Generated by DesignAgent | " . gmdate('Y-m-d H:i') . " UTC #}\n";
        @file_put_contents($path, $header . $html, LOCK_EX);

        // Update metadata index
        $this->updateMetadata($name, $filename, $metadata);

        return self::GENERATED_DIR . '/' . $filename;
    }

    /**
     * Load a component's HTML by name.
     */
    public function load(string $name): string
    {
        $name = $this->sanitizeName($name);
        $base = $this->base();

        // Try generated dir first, then main components dir
        foreach ([self::GENERATED_DIR, self::COMPONENT_DIR] as $dir) {
            $path = $base . '/' . $dir . '/' . $name . '.twig';
            if (is_file($path)) {
                return (string)file_get_contents($path);
            }
        }

        return '';
    }

    /**
     * List all components in the library.
     *
     * @return list<array{name: string, path: string, type: string, created_at: string, prompt?: string}>
     */
    public function list(): array
    {
        $meta = $this->readMetadata();
        return array_values($meta['components'] ?? []);
    }

    /**
     * Delete a component by name.
     */
    public function delete(string $name): bool
    {
        $name = $this->sanitizeName($name);
        $base = $this->base();
        $path = $base . '/' . self::GENERATED_DIR . '/' . $name . '.twig';

        if (!is_file($path)) {
            return false;
        }

        @unlink($path);

        // Remove from metadata
        $meta = $this->readMetadata();
        unset($meta['components'][$name]);
        $this->writeMetadata($meta);

        return true;
    }

    /**
     * Get preview HTML for a component (strips Twig comments/tags for safe preview).
     */
    public function preview(string $name): string
    {
        $html = $this->load($name);
        // Strip Twig comments
        $html = preg_replace('/\{#.*?#\}/s', '', $html) ?? $html;
        // Replace Twig variables with placeholder text
        $html = preg_replace('/\{\{.*?\}\}/', '[dynamic value]', $html) ?? $html;
        // Strip Twig blocks
        $html = preg_replace('/\{%.*?%\}/s', '', $html) ?? $html;
        return trim($html);
    }

    // ─── Private helpers ─────────────────────────────────────────────────────

    private function sanitizeName(string $name): string
    {
        return strtolower(preg_replace('/[^a-z0-9\-_]/', '-', strtolower($name)) ?? 'component');
    }

    private function base(): string
    {
        return defined('BASE_PATH') ? BASE_PATH : dirname(__DIR__, 4);
    }

    /**
     * @param array<string, mixed> $metadata
     */
    private function updateMetadata(string $name, string $filename, array $metadata): void
    {
        $meta = $this->readMetadata();
        if (!is_array($meta['components'] ?? null)) {
            $meta['components'] = [];
        }
        $meta['components'][$name] = array_merge([
            'name'       => $name,
            'path'       => self::GENERATED_DIR . '/' . $filename,
            'type'       => 'generic',
            'created_at' => gmdate('c'),
        ], $metadata);
        $this->writeMetadata($meta);
    }

    /**
     * @return array<string, mixed>
     */
    private function readMetadata(): array
    {
        $base = $this->base();
        $path = $base . '/' . self::METADATA_FILE;
        if (!is_file($path)) {
            return ['components' => []];
        }
        $raw = @file_get_contents($path);
        $j = is_string($raw) ? json_decode($raw, true) : null;
        return is_array($j) ? $j : ['components' => []];
    }

    /**
     * @param array<string, mixed> $meta
     */
    private function writeMetadata(array $meta): void
    {
        $base = $this->base();
        $dir  = $base . '/data/evolution';
        if (!is_dir($dir)) {
            @mkdir($dir, 0755, true);
        }
        $path = $base . '/' . self::METADATA_FILE;
        @file_put_contents($path, json_encode($meta, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
    }
}
