<?php

declare(strict_types=1);

namespace App\Core\Evolution;

use App\Core\Container;

/**
 * Semantic Documentation: auto-updates ARCHITECTURE.md after successful patches.
 *
 * After each auto_apply or shadow_swap, appends a changelog entry and
 * asks the AI to regenerate the relevant section of the architecture doc.
 */
final class SemanticDocService
{
    private const DOC_FILE = 'ARCHITECTURE.md';
    private const CHANGELOG_FILE = 'storage/evolution/architecture_changelog.jsonl';

    /**
     * Record a successful change for documentation purposes.
     */
    public static function recordChange(array $change): void
    {
        $entry = [
            'ts' => gmdate('c'),
            'target' => (string)($change['target'] ?? ''),
            'type' => (string)($change['type'] ?? 'php'),
            'severity' => (string)($change['severity'] ?? ''),
            'summary' => (string)($change['summary'] ?? ''),
            'auto' => (bool)($change['auto'] ?? true),
        ];

        $path = BASE_PATH . '/' . self::CHANGELOG_FILE;
        $dir = dirname($path);
        if (!is_dir($dir)) {
            @mkdir($dir, 0755, true);
        }
        @file_put_contents($path, json_encode($entry, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n", FILE_APPEND | LOCK_EX);
    }

    /**
     * Generate/update ARCHITECTURE.md based on recent changes.
     * Called periodically (e.g. after Ghost Mode) or manually.
     */
    public function updateArchitectureDoc(Container $container): array
    {
        $changes = $this->loadRecentChanges(30);
        if ($changes === []) {
            return ['ok' => true, 'updated' => false, 'reason' => 'No recent changes to document'];
        }

        $currentDoc = '';
        $docPath = BASE_PATH . '/' . self::DOC_FILE;
        if (is_file($docPath)) {
            $currentDoc = (string)@file_get_contents($docPath);
        }

        $prompt = $this->buildDocPrompt($currentDoc, $changes);

        $manager = new SelfHealingManager($container);
        $health = (new HealthSnapshotService())->snapshot($container);
        $result = $manager->architectChat(
            [['role' => 'user', 'content' => $prompt]],
            'core',
            false,
            1,
            ['user_id' => 0, 'listing_id' => 0],
            false,
            '',
            $health
        );

        if (!($result['ok'] ?? false)) {
            return ['ok' => false, 'updated' => false, 'error' => $result['error'] ?? 'AI call failed'];
        }

        $raw = $result['raw_json'] ?? [];
        $docContent = (string)($raw['architecture_doc'] ?? $raw['summary'] ?? '');
        if (trim($docContent) === '') {
            $docContent = $result['reply_text'] ?? '';
        }

        if (trim($docContent) !== '' && strlen($docContent) > 100) {
            $header = "# Architecture\n\n> Auto-generated by AI Architect — last updated: " . gmdate('Y-m-d H:i') . " UTC\n\n";
            @file_put_contents($docPath, $header . $docContent);

            EvolutionLogger::log('semantic_docs', 'updated', [
                'doc_path' => $docPath,
                'changes_documented' => count($changes),
                'doc_bytes' => strlen($docContent),
            ]);

            return ['ok' => true, 'updated' => true, 'changes_documented' => count($changes)];
        }

        return ['ok' => true, 'updated' => false, 'reason' => 'AI response too short for documentation'];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function loadRecentChanges(int $days): array
    {
        $path = BASE_PATH . '/' . self::CHANGELOG_FILE;
        if (!is_file($path)) {
            return [];
        }
        $cutoff = gmdate('c', time() - $days * 86400);
        $entries = [];
        $lines = @file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
        foreach ($lines as $line) {
            $j = @json_decode($line, true);
            if (is_array($j) && ($j['ts'] ?? '') >= $cutoff) {
                $entries[] = $j;
            }
        }

        return $entries;
    }

    private function buildDocPrompt(string $currentDoc, array $changes): string
    {
        $parts = [
            'ARCHITECTURE DOCUMENTATION UPDATE',
            '',
            'Generate an updated ARCHITECTURE.md for this PHP 8.3 marketplace framework.',
            'Include: data flow, key services, recent AI-driven changes, and architectural decisions.',
            '',
            'Respond with JSON: { "architecture_doc": "full markdown content", "summary": "what changed" }',
            '',
        ];

        if ($currentDoc !== '') {
            $parts[] = 'CURRENT ARCHITECTURE.md (update, do not rewrite from scratch):';
            $parts[] = substr($currentDoc, 0, 8000);
            $parts[] = '';
        }

        $parts[] = 'RECENT CHANGES (' . count($changes) . ' in last 30 days):';
        foreach (array_slice($changes, -20) as $c) {
            $auto = ($c['auto'] ?? false) ? 'auto' : 'manual';
            $parts[] = "  - [{$c['type']}] [{$c['severity']}] [{$auto}] {$c['target']}: {$c['summary']}";
        }

        return implode("\n", $parts);
    }
}
